### ISSUE TITLE
Problems using D3-geometer with D3v4

### ISSUE THREAD

**Issue by AndreaSimeone** [christabor/d3.geometer#4]
Any possibility to use Geometer with D3v4?
Lot of issues trying to use your library with the new version of D3

**Comment by christabor** [comment]
I have not tried it with the new version - I'll take a look and see what kind of errors I get.

**Comment by christabor** [comment]
What version did you try and what specific problems did you have? ~~I just swapped the v3 version with `https://cdnjs.cloudflare.com/ajax/libs/d3/4.7.1/d3.min.js` in the examples directory and it still works fine.~~ actually I'm seeing some errors. I'll take a long, but let me know what you are seeing as well.

**Comment by christabor** [comment]
I went through the d3 v4 CHANGES docs and made the relevant updates. It seems to be working for both now! Let me know if I missed something. I have not looked at this plugin for some time.

**Comment by AndreaSimeone** [comment]
Thanks, now works like a charm! 
Just another question(probably is just my fault): I've some problems with ngons and rotations (I want visualize shapes with odd sides with Y axes simmetry) but can't figure out how to obtain rotation.
Example:
```javascript   
     var root = d3.select("svg").append("g").attr("id","container");
     var ngon = d3_geometer.NGon(root);
     ngon(width / 6, 3)
     .drawVertices()
     .drawLabels()
     .drawPerimeterInteriorAngles()
     .calculateEdgeOffsets()
     .move(width / 2, height / 2)
     .rotate(-30,"root");
```

This chunk of code doesn't produce any rotation effect. If I pass the D3 selector to the rotate function an error occur:

> Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '[object Object]' is not a valid selector.

What's the correct way to implement rotation?
Thanks!
